spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<path>.*), /$\{path}
        - id: RequestService
          uri: http://localhost:8082
          predicates:
            - Path=/api/request/**
          filters:
            - RewritePath=/api/request/(?<path>.*), /$\{path}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
